import {
  ArrowSwitchIcon,
  BeakerIcon,
  BookIcon,
  ChecklistIcon,
  CircleSlashIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CodeReviewIcon,
  CommentDiscussionIcon,
  CopilotIcon,
  CreditCardIcon,
  DatabaseIcon,
  DeviceDesktopIcon,
  DeviceMobileIcon,
  EyeIcon,
  FileCodeIcon,
  FileIcon,
  GitPullRequestIcon,
  GraphIcon,
  InfinityIcon,
  KeyIcon,
  MailIcon,
  NoteIcon,
  PencilIcon,
  PeopleIcon,
  PulseIcon,
  RepoLockedIcon,
  RocketIcon,
  SearchIcon,
  ServerIcon,
  ShieldCheckIcon,
  ShieldLockIcon,
  ToolsIcon,
  UnlockIcon,
  WorkflowIcon,
  type Icon,
} from "@primer/octicons-react";
import type { ServiceIcon } from "@/lib/services";

/**
 * Content icons: Primer Octicons (GitHub's icon set), keyed by name so copy files in `src/lib`
 * stay free of component imports. Interface glyphs (chevrons, ticks) stay on Lucide.
 */
export const ICONS: Record<ServiceIcon, Icon> = {
  fileText: FileIcon,
  penTool: PencilIcon,
  code: CodeIcon,
  cloud: CloudIcon,
  presentation: DeviceDesktopIcon,
  rocket: RocketIcon,
  users: PeopleIcon,
  gitPullRequest: GitPullRequestIcon,
  wrench: ToolsIcon,
  bookOpen: BookIcon,
  workflow: WorkflowIcon,
  server: ServerIcon,
  shieldCheck: ShieldCheckIcon,
  activity: PulseIcon,
  piggyBank: CreditCardIcon,
  fileCode: FileCodeIcon,
  sparkles: CopilotIcon,
  listChecks: ChecklistIcon,
  flaskConical: BeakerIcon,
  scanSearch: SearchIcon,
  notebookPen: NoteIcon,
  brainCircuit: CopilotIcon,
  database: DatabaseIcon,
  userCheck: CodeReviewIcon,
  keyRound: KeyIcon,
  fingerprint: ShieldLockIcon,
  folderLock: RepoLockedIcon,
  power: CircleSlashIcon,
  smartphone: DeviceMobileIcon,
  mailOpen: MailIcon,
  clock: ClockIcon,
  messagesSquare: CommentDiscussionIcon,
  infinity: InfinityIcon,
  arrowSwitch: ArrowSwitchIcon,
  unlock: UnlockIcon,
  eye: EyeIcon,
  graph: GraphIcon,
};
